[project]
name = "2025_computer_vision"
version = "2025.spring.0"  # <year>.<quarter>.<revision #>
description = "Notes for the 2025 Intro to Computer Vision demo."
authors = ["Nick Ulle <naulle@ucdavis.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
build = { cmd = "jupyter-book build .", description = "Build the reader." }
publish = { cmd = "ghp-import --no-jekyll --no-history --push _build/html", description = "Publish the reader to the `gh-pages` branch on GitHub." }
clean = { cmd = "rm -rf _build/", description = "Remove the build directory." }
rebuild = { depends-on = ["clean", "build"], description = "Remove the build directory and build the reader." }

[dependencies]
python = ">=3.13.3,<3.14"
jupyter-book = ">=1.0.4.post1,<2"
ghp-import = ">=2.1.0,<3"
